<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.17">
  <POU Name="MAIN" Id="{7b9c8698-7ce0-48af-9cd6-368a0771761d}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR

END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
PRG_ZF_Control();
PRG_Engine();
PRG_BlinkMarine();
PRG_Ballast();
PRG_Doors();
PRG_Winches();
PRG_SimDoors();


]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>